### ISSUE TITLE
starting 0.3 results in SIGSEGV

### ISSUE THREAD

**Issue by swayamraina** [swayamraina/fcd#8]
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x128aabf]

goroutine 1 [running]:
main.check_sync.func1(0xc00012a0c0, 0x2f, 0x0, 0x0, 0x1386dc0, 0xc0004db680, 0xc0000cbd60, 0x1289ead)
	/Users/swayam.raina/opensrc/fcd/src/os_handler.go:64 +0x2f
path/filepath.Walk(0xc00012a0c0, 0x2f, 0xc00029a830, 0xc0004c8100, 0xc000326d00)
	/usr/local/go/src/path/filepath/path.go:402 +0x6a
main.scan(0xc0000cbe40, 0x128989a, 0x1322cab, 0x4)
	/Users/swayam.raina/opensrc/fcd/src/daemon.go:74 +0x68
main.scan_all(0xc0000de1c0, 0xc0000de201, 0x0, 0xc0000cbea8)
	/Users/swayam.raina/opensrc/fcd/src/daemon.go:60 +0xc1
main.daemon(0xc0000cbf20)
	/Users/swayam.raina/opensrc/fcd/src/daemon.go:39 +0x76
main.main()
	/Users/swayam.raina/opensrc/fcd/src/main.go:21 +0x72
```

**Comment by swayamraina** [comment]
caused by https://github.com/swayamraina/fcd/issues/9
trying to read path which does not exists
